name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  super-linter:
    name: All
    uses: harryzcy/github-actions/.github/workflows/linter.yml@81aad314153d8b8fd8dc8cfa277e1a2f637992fa # main

  spelling:
    name: Spelling
    uses: harryzcy/github-actions/.github/workflows/spelling.yml@81aad314153d8b8fd8dc8cfa277e1a2f637992fa # main
