name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  super-linter:
    name: All
    uses: harryzcy/github-actions/.github/workflows/linter.yml@1ea62348150d44bc99a8bf88a12438a9ecffd323 # main

  spelling:
    name: Spelling
    uses: harryzcy/github-actions/.github/workflows/spelling.yml@1ea62348150d44bc99a8bf88a12438a9ecffd323 # main
