name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  super-linter:
    name: All
    uses: harryzcy/github-actions/.github/workflows/linter.yml@4ebcdf92829ed99e2415853b7122f808008b23bf # main

  spelling:
    name: Spelling
    uses: harryzcy/github-actions/.github/workflows/spelling.yml@4ebcdf92829ed99e2415853b7122f808008b23bf # main

  renovate:
    name: Renovate
    uses: harryzcy/github-actions/.github/workflows/renovate.yml@4ebcdf92829ed99e2415853b7122f808008b23bf # main
